[build]
builder = "DOCKERFILE"
dockerfilePath = "conversai/rag-service/Dockerfile"

[deploy]
startCommand = "./conversai-rag"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10